arch:
  - "amd64"
  - "arm64"
dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
install:
- npm install
script: npm run lint && npm test
before_deploy: npm run mark && npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: IzhxBaWpxhzTzN4nGYKGez3qjZWSpxE2wUMvFvsw0KdxeXHzE5/JP3nbUDEtKjtrzaY4IzTL07DqM8ahtlSZzTwOMukneZ7t2v7Qe3q1PJs5CuagVu/Rbn9DJpo3lGIMACYsJuu51/Uv3p6JiRzp3mcUiLuCJInldlFzTAdlFgde2qlGSQJxOpZYs/LLkGjciUDcZWMMnoONb+ZvDFtBHu7avN2LuV+1yhH0PcRtPLx+/pNMeSBzD1Bpd1/bEciJmEI6FrlpCS0ErGRse5ORtPOZRHaSFwFhhsDsTbf0CkKsx+fqH64JJVjeilNYJqdVobMeCrmOoXopdhOc9Pu/EJCoraWwWrLZxvzHp7X9/a6kTqZZaTr+OQDiPSmkfR9OtiwJazq2ammNQ5DuaOunnMC37HyjCLpJF77g70J+8qcQueAAuPeyUHoCzM0cJzGQa2y2izqB5Z6oKlOv80dXSUxhshx6jQbLyjcdtJGTPRCknGDYqqeA0UBqg5qfqbT4BWowUJVZUXlYZaRraALPiq8gmlpJKuPOL/m/mbt7dUoWHKG8Z8jdTFDGvStJuE7KDTIzXpvwFFt4NGbYPwUujg0VJLWJXzg7vWT5Qe4Qs0pm3+5QVMcR6rBEaaPfrUTar2LyRgkWQgzmpbsQp7E6b8Tyf3c0Yb2c/LAW3WNEk0c=
  on:
    tags: true
    arch: "amd64"
    node_js: "10"
env:
  matrix:
    secure: DcyK0cJ6/uIdseHkp9nPPig8nG1QqRACQgau2xY/hrpgVZ8FuzE1M5RPJSxzYd9+qjItCAJpx3lw3d24YPSn7XChYmcBlwF69QyP8k/bsdrQuMgwfYOvZmfOZZTvtXPUvIro4bGBih447rF+9KY3FsSXBCEqkR0POaQcuMAOeV+H1EKSZFBGTYGMrmPW6TwQJtICJM1ch+1C9OTAH2GWhH9CulZjM+Kcao05eqiDnNOdLvaeS1vCR3BE6J38fA2Yn9/Ta96auZ4E5rX8JtoK8AqXKoiMksrFocp7ke7GWPYpo0ewzfYudzQ0QzZZaD3fXxOrEsEDRzAkrhaGsZClrNT5fd6Sec8UZBTYB2D86Zq1IRt9uTblEga9tRlNhePf9+CcN5JtAWZfr6QySNx0B2Gkcn0fNEM5H7f17vMlL8OnYTWTp7TN06ARyw+WhgyAl2ODFPLyK8Fxui95PQEdeKbs0PThU4jntqd1WwvvIa+NsK+SGG+XCURhvdcGrF09HieM6YMD1oVtHP+ulxjrFCth7DM7LdqWQaLX73pT6/RxqtmmFOuD0oeEK6wx/tvmHlLana2YR3G0ymDGIfrRjUsDvRUn7jQ+rIoTlA57ZhQ0u0zUTwiDUN1osn5GG+tTtQTouBkqKCu6if8JxNDA1VOPBsAP95HEkvIqhM1rEN4=
