dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
install:
- npm install
script: npm run lint && npm test
before_deploy: npm run mark && npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: IzhxBaWpxhzTzN4nGYKGez3qjZWSpxE2wUMvFvsw0KdxeXHzE5/JP3nbUDEtKjtrzaY4IzTL07DqM8ahtlSZzTwOMukneZ7t2v7Qe3q1PJs5CuagVu/Rbn9DJpo3lGIMACYsJuu51/Uv3p6JiRzp3mcUiLuCJInldlFzTAdlFgde2qlGSQJxOpZYs/LLkGjciUDcZWMMnoONb+ZvDFtBHu7avN2LuV+1yhH0PcRtPLx+/pNMeSBzD1Bpd1/bEciJmEI6FrlpCS0ErGRse5ORtPOZRHaSFwFhhsDsTbf0CkKsx+fqH64JJVjeilNYJqdVobMeCrmOoXopdhOc9Pu/EJCoraWwWrLZxvzHp7X9/a6kTqZZaTr+OQDiPSmkfR9OtiwJazq2ammNQ5DuaOunnMC37HyjCLpJF77g70J+8qcQueAAuPeyUHoCzM0cJzGQa2y2izqB5Z6oKlOv80dXSUxhshx6jQbLyjcdtJGTPRCknGDYqqeA0UBqg5qfqbT4BWowUJVZUXlYZaRraALPiq8gmlpJKuPOL/m/mbt7dUoWHKG8Z8jdTFDGvStJuE7KDTIzXpvwFFt4NGbYPwUujg0VJLWJXzg7vWT5Qe4Qs0pm3+5QVMcR6rBEaaPfrUTar2LyRgkWQgzmpbsQp7E6b8Tyf3c0Yb2c/LAW3WNEk0c=
  on:
    tags: true
    node_js: "10"
env:
  matrix:
    secure: AmXl0PliySJB6HwM8NzxO/3l5Axa60UnrodsEs3sJ+EdFAgwgfa8Lj8CvWDFiz7hgg37KXgjPHuF+oUcYcAWkArAZBvqf7RvjZEB8+l3TvAlELCghDpSqbmzonGr6elJmA/NY7FGYOQ5JlwyUadVE112Nhg1oI6Q9IptJNBA2HXGzc5iqRoa1jJrAgE6GGzw+5D6Urj3TFDrtL/FVhf5PM+80tgUUUNibDYZPBZHsR05CIei9fXynyDhieMt561cLHyR0SOFu8oD1r0Nq7wHTzzZkGVaaGSEF+bC/YJLndonLWq4IYKBWnozesOVEsTMF0dcEpw5MS9Xfi/q1DvFZX+sJ8g4UJ93iZrHBD/h21HDe/KTE2AsRg/5dx3M1+MsFShRHasIusqlEqdUhrqf1/dd5TIYEFJn9DfhdGbXrxz/f52Y6L64VCkQSmEfXVXJgHowKCEgjshWv7SmIp+gcWMjNDU3ojCvAqn/J+h9gky6NaEvlm9kFrkDpf0T6EIPrgG4XrKLBNE/Ixf1Sc+37S/tJ/s80d3YWSs90WPkOPwI0DT+fKiEDzyfi8Td9TyU5gdX+SFTX2MW52qRqZjrqhJB2HirBiC8KRPMNtRHiW8ke5UUP8pz1kRoKhZf5QWQVgSJR+7UR9dtTOQbxmT1R+gx9/sxdYog418UuLVbgFQ=
