dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
install:
- npm install
script: npm run lint && npm test
before_deploy: npm run mark && npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: IzhxBaWpxhzTzN4nGYKGez3qjZWSpxE2wUMvFvsw0KdxeXHzE5/JP3nbUDEtKjtrzaY4IzTL07DqM8ahtlSZzTwOMukneZ7t2v7Qe3q1PJs5CuagVu/Rbn9DJpo3lGIMACYsJuu51/Uv3p6JiRzp3mcUiLuCJInldlFzTAdlFgde2qlGSQJxOpZYs/LLkGjciUDcZWMMnoONb+ZvDFtBHu7avN2LuV+1yhH0PcRtPLx+/pNMeSBzD1Bpd1/bEciJmEI6FrlpCS0ErGRse5ORtPOZRHaSFwFhhsDsTbf0CkKsx+fqH64JJVjeilNYJqdVobMeCrmOoXopdhOc9Pu/EJCoraWwWrLZxvzHp7X9/a6kTqZZaTr+OQDiPSmkfR9OtiwJazq2ammNQ5DuaOunnMC37HyjCLpJF77g70J+8qcQueAAuPeyUHoCzM0cJzGQa2y2izqB5Z6oKlOv80dXSUxhshx6jQbLyjcdtJGTPRCknGDYqqeA0UBqg5qfqbT4BWowUJVZUXlYZaRraALPiq8gmlpJKuPOL/m/mbt7dUoWHKG8Z8jdTFDGvStJuE7KDTIzXpvwFFt4NGbYPwUujg0VJLWJXzg7vWT5Qe4Qs0pm3+5QVMcR6rBEaaPfrUTar2LyRgkWQgzmpbsQp7E6b8Tyf3c0Yb2c/LAW3WNEk0c=
  on:
    tags: true
    node_js: "10"
env:
  matrix:
    secure: L32bYJotevaEkEECm/eYbT0JcdXZOlDS1J2NA7/rOAnTkl1iBeYI9JgXwkkud08XoWVfker5TDMmPT8xHCZDTR476UwjWKi63Zn9wUv/NI7jNnNghOPQem65E/v4oO41zMoT124Fbd6wnJiQX01TOp+/W+3gz1y2Y8besW+5aQWszyQ96f63QhlngHbViEP+EvvePtFuhIbi/Ag9FrxDX931bmUaVNy/7c5PDAyANTOXNUU8MhwEYSMOwO/pjiWAQ/quetuXISyLbx8WO45tXDEYYeboD1u+lCNr+LSbyFTInldiqoFQISMXdFDIeh5GmlYwor2Le/Gp8PkS8DwyckBWVdT4x3aIfLzmXrqs6/RxrrLCQH8DJSedl94goVRLRQzpUBEV2gy6Sh9NVqzV2Fzx8jSCC22s8kpTZpxK+okKraYmVUiHfeqjhjzc1/SAtPt7yKFTr2+9FyHR5cgm3p2fl5VPxcDKR/RfxLrZ3GtV+jadQYAlVMeXJPEnu4MLUnUsvdplidtcmPjScHhbeZTP9V1QvyWNJkkoMxenBmrB0/2++9QSQf2Hild+RXuWI8MjhKctXMtvpyBsT7EmmuiTrp8JDoG+D4P2q3qddkg7mscrYuxGuaFzovYS3zSvF8lDgdnuWTLaI7U0tfc4H7s6U28ji25srsmIiUAaoII=
